#application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-app
  namespace: argocd
spec:
  project: devops
  source:
     repoURL: https://github.com/Tykama/argo-testing-repo.git
     targetRevision: HEAD
     path: prod
  destination:
    server: eks-cluster
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true