apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tony
  name: tony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tony
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tony
    spec:
      containers:
      - image: nginx
      #  image: tonyit1985/ngnix: 2.0.0
        name: kubenginx
        ports:
        - containerPort: 80
        resources: {}

#To be sent to your GitHub repo.
#Change the image name to your own image name.